name: Release

on:
  push:
    branches: 
      - main
      - dev

jobs:
  #eavfw_test:
  #  uses: ./.github/workflows/testeavfw.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    #needs:
    #  - "eavfw_test"  
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits --force
      working-directory: ./.github/workflows

    - name: NPM Install
      run: npm ci --force

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GIT_AUTHOR_NAME: pksorensen
        GIT_AUTHOR_EMAIL: poul@kjeldager.com
      run: npm run release

    #- name: Release EAVFW/Apps
    #  working-directory: ./packages/apps
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #    GIT_AUTHOR_NAME: pksorensen
    #    GIT_AUTHOR_EMAIL: poul@kjeldager.com
    #  run: npx semantic-release

    #- name: Release EAVFW/Expressions
    #  working-directory: ./packages/expressions
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    #    GIT_AUTHOR_NAME: pksorensen
    #    GIT_AUTHOR_EMAIL: poul@kjeldager.com
    #  run: npx semantic-release