name: Build and Test EAVFW

on:
  workflow_call:
    inputs:
      templateversion:
        required: false
        default: '2.1.6-dev.5'
        type: string
      react_type_version:
        required: false
        default: '17.0.75'
        type: string
      dotnetversion:
        required: false
        default: '6.0.308'
        type: string
      nodeversion:
        required: false
        default: '20'
        type: string
      
        
jobs:
  eavfw_job:
    name: Build and Test EAVFW
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      # - uses: actions/setup-dotnet@v3
      #   with:
      #     dotnet-version: ${{ inputs.dotnetversion }}

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ inputs.nodeversion }}
          
      # - name: install EAVFW template
      #   run: (dotnet new --debug:rebuildcache) -and (dotnet new --install EAVFW.Templates::${{ inputs.templateversion }}) -and (dotnet new --uninstall)

      # - name: link
      #   run: npm install --force --ignore-scripts

      # - name: link
      #   run: npm run link

      # - name: create directory for test project
      #   run: mkdir ./../GithubEAVTestDirectory

      # - name: create test project from template with no extensions
      #   run: ( dotnet new --debug:rebuildcache) -and (dotnet new eavfw --namespace "GithubTestOrg" --appName "GithubTestApp" --databaseName "GithubTestDB" --skipGitCommit --allow-scripts yes --dotnetSDK ${{ inputs.dotnetversion }} --reactTypesVersion ${{ inputs.react_type_version }} --skipPortal)
      #   working-directory: "./../GithubEAVTestDirectory"

      # - name: create test web portal from template
      #   run: npm run eavfw-nextjs
      #   working-directory: "./../GithubEAVTestDirectory"
 
      # - name: Install NPM
      #   run: npm install --force
      #   working-directory: "./../GithubEAVTestDirectory"

      # - name: LINK EAVFW
      #   run: npm run eavfw-link --force
      #   working-directory: "./../GithubEAVTestDirectory"
        
      # - name: build and export web portal
      #   run: npm run build
      #   working-directory: "./../GithubEAVTestDirectory"
